name = "nakama-frontend"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-07-22"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_API_BASE = "https://mynakama.web.id"