#!/usr/bin/env python3
"""Scaffold a new source adapter."""
import argparse, datetime as dt, re, sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
SOURCES = PROJECT / "app" / "sources"

KIND_CFG = {
    "anime": ("AnimeSource", "detail", "episode"),
    "comic": ("ComicSource", "manga",  "chapter"),
    "novel": ("NovelSource", "detail", "chapter"),
}


def class_name(slug):
    return "".join(p.capitalize() for p in re.split(r"[-_]+", slug)) + "Source"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("name")
    p.add_argument("--host", required=True)
    p.add_argument("--kind", choices=["anime", "comic", "novel"], default="comic")
    args = p.parse_args()
    name = args.name.lower()
    if not re.match(r"^[a-z][a-z0-9-]+$", name):
        print(f"ERROR: bad name '{args.name}'", file=sys.stderr); return 1
    target = SOURCES / f"{name}.py"
    if target.exists():
        print(f"ERROR: {target} exists", file=sys.stderr); return 1
    base_cls, detail_m, chapter_m = KIND_CFG[args.kind]
    today = dt.date.today().isoformat()
    cls = class_name(name)
    body = f'''"""{cls} — {args.kind} source for {name}.

Auto-generated by scripts/scaffold_source.py. Fill in selectors + URL
patterns then register in app/sources/registry.py.
"""
from __future__ import annotations
from typing import List
from ..http import fetch_soup
from .base import {base_cls}, SourceError
from .source_meta import SourceMeta

BASE = "https://{args.host}"


class {cls}({base_cls}):
    name = "{name}"
    base_url = BASE

    meta = SourceMeta(
        version="{today}",
        verified_on="{today}",
        base_url_pattern="https://{args.host}/<slug>/",
        selectors=[".card", ".list a"],
        alt_domains=[],
        notes="",
    )

    async def home(self, page: int = 1) -> List[dict]:
        url = self.base_url if page == 1 else f"{{self.base_url}}/page/{{page}}"
        soup = await fetch_soup(url, source=self.name)
        return _parse_listing(soup)

    async def search(self, query: str) -> List[dict]:
        soup = await fetch_soup(f"{{self.base_url}}/search", params={{"q": query}}, source=self.name)
        return _parse_listing(soup)

    async def {detail_m}(self, slug: str) -> dict:
        soup = await fetch_soup(f"{{self.base_url}}/{{slug}}", source=self.name)
        return _parse_detail(soup, slug)

    async def {chapter_m}(self, slug: str) -> dict:
        soup = await fetch_soup(f"{{self.base_url}}/{{slug}}", source=self.name)
        return _parse_chapter(soup, slug)

    async def genres(self) -> List[dict]:
        soup = await fetch_soup(f"{{self.base_url}}/genres", source=self.name)
        return _parse_genres(soup)


def _parse_listing(soup): return []
def _parse_detail(soup, slug): return {{"slug": slug}}
def _parse_chapter(soup, slug): return {{"slug": slug}}
def _parse_genres(soup): return []
'''
    target.write_text(body)
    print(f"created: {target}")
    print()
    print("Next steps:")
    print(f"  1. Edit selectors in app/sources/{name}.py")
    print(f"  2. Add to app/sources/registry.py:")
    print(f'       _REGISTRY["{name}"] = {cls}()')
    print(f"  3. Add domain to deploy/watchdog-domains.sh:")
    print(f'       "{args.host}"    # {name} ({args.kind})')
    return 0


if __name__ == "__main__":
    sys.exit(main())